@startuml

cloud tomcat {
    component cwms_aaa as "cwms-aaa
        <host>/CWMSLogin/"
    component cwms_data_api as "cwms-data-api
        <host>/cwms-data/"
}

package "cda_client repo" {

    component cwms_aaa_client as "cwms-aaa-client
        mil.army.usace.hec.cwms.aaa.client"
    note bottom of cwms_aaa_client : Performs calls to CWMS_AAA
    component cwms_http_client as "cwms-http-client
        mil.army.usace.hec.cwms.http.client"
    note right of cwms_http_client
        Fluent API for HTTP
        communications and authentication
    end note
    component cwms_data_api_client as "cwms-data-api-client
        mil.army.usace.hec.cwms.data.api.client.controllers"
    note right of cwms_data_api_client : Performs calls to CDA

    component cwms_data_api_model as "cwms-data-api-model
        mil.army.usace.hec.cwms.data.api.client.model"
    note right of cwms_data_api_model : CDA data parsing

}
legend top right
    group: mil.army.usace.hec
end legend


cwms_data_api_client -left[hidden]- cwms_aaa_client

cwms_aaa <.down.> cwms_http_client : CWMS_AAA login (https)
cwms_http_client <.down.> cwms_aaa_client : Uses http client for login


cwms_data_api <.down.> cwms_http_client : CDA read/write (https)
cwms_http_client <.down.> cwms_data_api_client : Uses http client for get/post

cwms_http_client <-down- cwms_aaa_client
cwms_http_client <-down- cwms_data_api_client

cwms_data_api_client -down-> cwms_data_api_model

@enduml
