name: Generate badges
on:
  push:
    branches:
      - main

jobs:
  build:
    name: generate and display coverage badge
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup java
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
      - name: test
        id: thebuild
        run: ./gradlew test --info --init-script init.gradle
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2.3.0
        with:
          generate-branches-badge: true
          jacoco-csv-file: cwms-radar-client/build/reports/jacoco/test/jacocoTestReport.csv
      - name: Commit and push Badges
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          cd .github/badges
          if [[ `git status --porcelain *.svg` ]]; then
            git config --global user.name 'builduser'
            git config --global user.email 'builduser@rmanet.com'
            git add *.svg
            git commit -m "Autogenerated JaCoCo coverage badge" *.svg
            git push
          fi
