name: Deploy cwms-data-api-client
on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5
      - name: setup java
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          java-package: jdk
          distribution: 'temurin'
      - name: Publish Artifacts
        id: thedeploy
        run: ./gradlew publish --info --init-script init.gradle
        env:
          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
